{
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/EAM_AssetManagerv2/Actions/mobileservices/Service/SyncFailureMessage.action",
	"OnSuccess": "/EAM_AssetManagerv2/Rules/mobileservices/ErrorArchive_CheckForSyncError.js",
	"Service": "/EAM_AssetManagerv2/Services/mobileservices.service",
	"DefiningRequests": [
		{
			"Name": "ZA_FunctionalLocation",
			"Query": "ZA_FunctionalLocation",
			"AutomaticallyRetrievesStreams": false
		}
	]
}