{
	"_Type": "Action.Type.ODataService.Initialize",
	"ActionResult": {
		"_Name": "init"
	},
	"OnFailure": "/EAM_AssetManagerv2/Actions/mobileservices/Service/InitializeOfflineFailureMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Downloading...",
	"Service": "/EAM_AssetManagerv2/Services/mobileservices.service",
	"DefiningRequests": [
		{
			"Name": "Customers",
			"Query": "Customers"
		}
	]
}