{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/EAM_AssetManagerv2/Actions/mobileservices/Service/UploadOffline.action",
    "OnFailure": "/EAM_AssetManagerv2/Actions/mobileservices/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}