{
	"_Type": "Action.Type.Filter",
	"ActionResult": {
		"_Name": "FunctionLoc_List_Filter"
	},
	"Filterable": "#Page:FunctionLoc_List/#Control:SectionedTable0",
	"PageToOpen": "/EAM_AssetManagerv2/Pages/FunctionalLocation/FunctionLoc_List_Filter.page"
}