{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavToFunctionalLoc_List"
	},
	"PageToOpen": "/EAM_AssetManagerv2/Pages/FunctionalLocation/FunctionLoc_List.page",
	"NavigationType": "Inner"
}